In [28]:
## STEPS FOR BUILDING A PROJECT

#1. Raw Customer Data
#2. preprocessing
#3. Feauture engineering
#4. Scaling
#5. Train Test split
#6. Build ANN Model
#7. Train the ANN model
#8. save the model
#9. Deploy it on streamlit
#Customer stayed=0
#customer left=1

In [29]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [30]:
# load the customer churn dataset.

data = pd.read_csv('Churn_Modelling.csv')

In [31]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [32]:
## preprocessing the data

data = data.drop(['RowNumber','CustomerId', 'Surname'], axis=1)

data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [33]:
## Featuring Engineering

label_encoder_gender = LabelEncoder()

In [34]:
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

data.head(10)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
5,645,Spain,1,44,8,113755.78,2,1,0,149756.71,1
6,822,France,1,50,7,0.00,2,1,1,10062.80,0
7,376,Germany,0,29,4,115046.74,4,1,0,119346.88,1
8,501,France,1,44,4,142051.07,2,0,1,74940.50,0
9,684,France,1,27,2,134603.88,1,1,1,71725.73,0

In [35]:
Onehotencoder_geography = OneHotEncoder()

geo_encoder = Onehotencoder_geography.fit_transform(data[['Geography']]).toarray()

geo_encoder

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [36]:
geo_encoded_df = pd.DataFrame(
    geo_encoder,
     columns=Onehotencoder_geography.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [37]:
data = pd.concat(
    [
        data.drop(['Geography'], axis=1),
        geo_encoded_df
    ],
    axis=1
)

data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [38]:
x = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [39]:
with open("LabelEncoder_Gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender,file)

with open("Onehotencoder_geography.pkl","wb") as file:
    pickle.dump(Onehotencoder_geography, file)

print("Encoder saved successfully.")

Encoder saved successfully.

In [40]:
# X = Features INPUT
# Y = Output/Target
Y = 'EstimatedSalary'

In [41]:
X = data.drop(
    "EstimatedSalary", axis=1
)

Y = data["EstimatedSalary"]

## For the regression workflow, X represents the input features and y represents
#  the EstimatedSalary as the target variable.


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [42]:
## In training data "fit.transform" is used
## In Testing data ".Transform" is used

Scaler = StandardScaler()
X_train = Scaler.fit_transform(X_train)
X_test = Scaler.transform(X_test)

In [44]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import datetime

ModuleNotFoundError: No module named 'tensorflow.python'

In [ ]:
## Building regression model

model = keras.Sequential([

keras.Input(shape=(X_train.shape[1],)),
      keras.layers.Dense(64,activation='relu'),
      keras.layers.Dense(32,activation='relu'),
      keras.layers.Dense(1,activation='linear')
])

model.summary()